Implement Identity services and token generation
EasyMicroservices/Identity-Microservice pull request #2
Opened 2023-11-21 14:37 UTC by MahdiyarGHD

2023-11-21 17:34 UTC, Hamed-Bagherpour approved these changes

2023-11-21 17:38 UTC, Ali-YousefiTelori requested changes

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Domain/Contracts/Responses/UserResponseContract.cs
> +        public string UniqueIdentity { get; set; }
We do not use UID in user response

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Domain/EasyMicroservices.IdentityMicroservice.Domain.csproj
> +		<Reference Include="EasyMicroservices.AuthenticationsMicroservice.Clients">
We have to remove this direct use

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Logics/Helpers/IdentityHelper.cs
> +        public async Task<MessageContract<long>> Register(Contracts.Requests.AddUserRequestContract request)
Please create RegisterResponseContract for this method

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Logics/Helpers/IdentityHelper.cs
> +        public virtual async Task<MessageContract<long>> Login(Contracts.Common.UserSummaryContract cred)
Please create LoginResponseContract for this method

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Logics/Helpers/IdentityHelper.cs
> +                return (ServiceContracts.FailedReasonType.AccessDenied, "Username or password is invalid."); //"Username or password is invalid."
We have Incorrect FailedReason, don't use AccessDenied.

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.WebApi/Controllers/IdentityController.cs
> +        public async Task<MessageContract<bool>> VerifyUserName(VerifyEmailAddressContract request)
Please add VerifyUserNameResponseContract.
Why VerifyUserName has VerifyEmailAddressContract for request?

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.WebApi/Controllers/IdentityController.cs
> +        public async Task<MessageContract<long>> Register(Contracts.Requests.AddUserRequestContract request)
Please add RegisterResponseContract

2023-11-21 17:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.WebApi/Controllers/IdentityController.cs
> +        public async Task<MessageContract<long>> Login(Contracts.Common.UserSummaryContract request)
Please Add LoginResponseContract

2023-11-22 11:09 UTC, mahdidelzendeh72 approved these changes
thanks

2023-11-22 16:38 UTC, Ali-YousefiTelori approved these changes

2023-11-22 16:38 UTC, merged