Add application initialize & cookie management
EasyMicroservices/Identity-Microservice pull request #6
Opened 2023-11-29 15:46 UTC by MahdiyarGHD

2023-11-30 12:55 UTC, Ali-YousefiTelori requested changes

2023-11-30 12:55 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Logics/Helpers/IdentityHelper.cs
> +            _userClient.SetBearerToken(_config.GetValue<string>("Authorization:FullAccessPAT"));
Please move SetBearerToken to GetClient

2023-11-30 12:55 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.IdentityMicroservice.Logics/Helpers/IdentityHelper.cs
> +            var loginResponse = await Login(userClaim);
Use AsCheckedRsesult

2023-11-30 13:04 UTC, Mohsen-Yaghoubi approved these changes

2023-12-02 15:30 UTC, AmirmohammadNemati approved these changes

2023-12-02 19:18 UTC, merged

2023-12-05 14:20 UTC, mahdidelzendeh72 reviewed
thanks